const TOPICS = {
  USER_REGISTRATION_OTP_SEND: 'user.registration.otp.send',
  USER_REGISTRATION_WELCOME_EMAIL: 'user.registration.welcome.email',
  USER_LOGIN_OTP_REQUESTED: 'user.login.otp.requested',
  EMAIL_NOTIFICATION: 'email.notification'
};

const EVENT_TYPES = {
  USER_REGISTRATION_OTP_SEND: 'USER_REGISTRATION_OTP_SEND',
  USER_REGISTRATION_WELCOME_EMAIL: 'USER_REGISTRATION_WELCOME_EMAIL',
  USER_LOGIN_OTP_REQUESTED: 'USER_LOGIN_OTP_REQUESTED',
  EMAIL_NOTIFICATION_REQUESTED: 'EMAIL_NOTIFICATION_REQUESTED'
};

module.exports = { TOPICS, EVENT_TYPES };
